import { API_ENDPOINTS } from '../config/api';

const TOKEN_STORAGE_KEY = 'access_token';
const USER_STORAGE_KEY = 'auth_user';
const FULL_NAME_MAP_KEY = 'preferred_full_names';
const PHONE_MAP_KEY = 'preferred_phone_numbers';

const parseErrorMessage = async (res, fallbackMessage) => {
  try {
    const data = await res.json();
    if (data?.error) return data.error;
    if (data?.message) return data.message;
    return fallbackMessage;
  } catch {
    return fallbackMessage;
  }
};

const requestJson = async (url, options, fallbackMessage) => {
  const res = await fetch(url, options);

  if (!res.ok) {
    const errorMessage = await parseErrorMessage(res, fallbackMessage);
    throw new Error(`${errorMessage}`);
  }

  if (res.status === 204) return null;
  return res.json();
};

export const register = async ({ email, password, fullName, username, phoneNumber }) => {
  const payload = {
    email,
    password,
    fullName,
    fullname: fullName,
    username,
    phoneNumber,
    phone: phoneNumber,
    phone_number: phoneNumber,
  };

  return requestJson(
    API_ENDPOINTS.AUTH_REGISTER,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    },
    'Đăng ký thất bại'
  );
};

export const login = async ({ email, password }) => {
  return requestJson(
    API_ENDPOINTS.AUTH_LOGIN,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    },
    'Đăng nhập thất bại'
  );
};

export const extractAccessToken = (payload) => {
  if (!payload || typeof payload !== 'object') return '';

  return (
    payload?.tokens?.accessToken ||
    payload?.tokens?.access_token ||
    payload?.accessToken ||
    payload?.access_token ||
    payload?.token ||
    payload?.data?.tokens?.accessToken ||
    payload?.data?.tokens?.access_token ||
    payload?.data?.accessToken ||
    payload?.data?.access_token ||
    payload?.data?.token ||
    ''
  );
};

export const getMyProfile = async () => {
  return requestJson(
    API_ENDPOINTS.USER_ME,
    {
      method: 'GET',
      headers: {
        ...getAuthHeaders(),
      },
    },
    'Không thể lấy thông tin người dùng'
  );
};

export const saveAccessToken = (token) => {
  if (!token) return;
  localStorage.setItem(TOKEN_STORAGE_KEY, token);
};

export const getAccessToken = () => {
  return localStorage.getItem(TOKEN_STORAGE_KEY);
};

export const clearAccessToken = () => {
  localStorage.removeItem(TOKEN_STORAGE_KEY);
};

export const getAuthHeaders = () => {
  const token = getAccessToken();
  if (!token) return {};
  return { Authorization: `Bearer ${token}` };
};

const getPreferredFullNameMap = () => {
  const raw = localStorage.getItem(FULL_NAME_MAP_KEY);
  if (!raw) return {};

  try {
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
};

const getPreferredPhoneMap = () => {
  const raw = localStorage.getItem(PHONE_MAP_KEY);
  if (!raw) return {};

  try {
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
};

export const savePreferredFullName = (email, fullName) => {
  const normalizedEmail = String(email || '').trim().toLowerCase();
  const normalizedName = String(fullName || '').trim();
  if (!normalizedEmail || !normalizedName) return;

  const currentMap = getPreferredFullNameMap();
  currentMap[normalizedEmail] = normalizedName;
  localStorage.setItem(FULL_NAME_MAP_KEY, JSON.stringify(currentMap));
};

export const getPreferredFullName = (email) => {
  const normalizedEmail = String(email || '').trim().toLowerCase();
  if (!normalizedEmail) return '';
  const currentMap = getPreferredFullNameMap();
  return currentMap[normalizedEmail] || '';
};

export const savePreferredPhoneNumber = (email, phoneNumber) => {
  const normalizedEmail = String(email || '').trim().toLowerCase();
  const normalizedPhone = String(phoneNumber || '').trim();
  if (!normalizedEmail || !normalizedPhone) return;

  const currentMap = getPreferredPhoneMap();
  currentMap[normalizedEmail] = normalizedPhone;
  localStorage.setItem(PHONE_MAP_KEY, JSON.stringify(currentMap));
};

export const getPreferredPhoneNumber = (email) => {
  const normalizedEmail = String(email || '').trim().toLowerCase();
  if (!normalizedEmail) return '';
  const currentMap = getPreferredPhoneMap();
  return currentMap[normalizedEmail] || '';
};

const isAutoGeneratedUsername = (username) => /^user[_-]/i.test(String(username || '').trim());

export const getDisplayName = (userInput) => {
  const user = userInput || getCurrentUser() || {};
  const fullName = String(user?.fullName || user?.fullname || '').trim();
  if (fullName) return fullName;

  const preferredFullName = getPreferredFullName(user?.email);
  if (preferredFullName) return preferredFullName;

  const username = String(user?.username || '').trim();
  if (username && !isAutoGeneratedUsername(username)) return username;

  return 'bạn';
};

export const saveCurrentUser = (user) => {
  if (!user) return;

  const existingUser = getCurrentUser() || {};
  const email = user?.email || existingUser?.email || '';
  const preferredFullName =
    user?.fullName ||
    user?.fullname ||
    existingUser?.fullName ||
    existingUser?.fullname ||
    getPreferredFullName(email);
  const preferredPhoneNumber =
    user?.phone_number ||
    user?.phoneNumber ||
    user?.phone ||
    existingUser?.phone_number ||
    existingUser?.phoneNumber ||
    existingUser?.phone ||
    getPreferredPhoneNumber(email);

  const normalizedUser = {
    ...existingUser,
    ...user,
  };

  if (preferredFullName) {
    normalizedUser.fullName = preferredFullName;
    savePreferredFullName(email, preferredFullName);
  }

  if (preferredPhoneNumber) {
    normalizedUser.phone_number = preferredPhoneNumber;
    normalizedUser.phoneNumber = preferredPhoneNumber;
    normalizedUser.phone = preferredPhoneNumber;
    savePreferredPhoneNumber(email, preferredPhoneNumber);
  }

  localStorage.setItem(USER_STORAGE_KEY, JSON.stringify(normalizedUser));
};

export const getCurrentUser = () => {
  const userRaw = localStorage.getItem(USER_STORAGE_KEY);
  if (!userRaw) return null;

  try {
    return JSON.parse(userRaw);
  } catch {
    return null;
  }
};

export const clearCurrentUser = () => {
  localStorage.removeItem(USER_STORAGE_KEY);
};

export const clearAuthSession = () => {
  clearAccessToken();
  clearCurrentUser();
};

export const TOKEN_KEY = TOKEN_STORAGE_KEY;
export const USER_KEY = USER_STORAGE_KEY;
